Repository boostcampwm2023/iOS07-traveline, pull requests merged in 2024-10, with the labels that each got.

#472 Revert "[feat] 파일 시스템으로 이미지를 관리하도록 하는 서비스 생성"
  BE/src/app.module.ts
  BE/src/app.service.ts
  BE/src/auth/auth.module.ts
  BE/src/file/file.module.ts
  BE/src/file/file.service.ts
  BE/src/postings/postings.module.ts
  BE/src/postings/postings.service.ts
  BE/src/timelines/timelines.module.ts
  BE/src/timelines/timelines.service.ts
  BE/src/users/users.module.ts
  BE/src/users/users.service.ts
Labels: 🛠️ Chore

#473 [feat] 파일 시스템으로 이미지를 관리하도록 하는 서비스 생성
  BE/src/app.module.ts
  BE/src/app.service.ts
  BE/src/auth/auth.module.ts
  BE/src/file/file.module.ts
  BE/src/file/file.service.ts
  BE/src/postings/postings.module.ts
  BE/src/postings/postings.service.ts
  BE/src/timelines/timelines.module.ts
  BE/src/timelines/timelines.service.ts
  BE/src/users/users.module.ts
  BE/src/users/users.service.ts
Labels: 💽 BE, ♻️ Refactor, 📁 Common

#476 [fix] Docker base img 수정
  BE/Dockerfile
Labels: 💽 BE

#477 [fix] 배포 yml 파일 동기화
  .github/workflows/deploy.yml
Labels: 💽 BE, 🐞 Bug

#478 Revert "[fix] Docker base img 수정"
  BE/Dockerfile
Labels: 💽 BE

#479 [fix] Docker base img 수정 (develop으로...)
  BE/Dockerfile
Labels: 💽 BE

#482 [fix] 배포 스텝 수정
  .github/workflows/deploy.yml
Labels: 💽 BE
